services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/library_management
    networks:
      - mern-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mern-network

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Attach persistent volume
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo_data: {} # Define the volume for MongoDB
