version: '3.8'

services:
  backend:
    image: ${DOCKER_USERNAME}/library-backend:latest
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/library_management
      - NODE_ENV=production
    networks:
      - mern-network

  frontend:
    image: ${DOCKER_USERNAME}/library-frontend:latest
    restart: always
    ports:
      - "80:3000"     # Keep port 80 for standard HTTP access
      - "3000:3000"   # Also map port 3000 for WebSocket connections
    environment:
      - REACT_APP_API_URL=http://${SERVER_IP}:5000  # Dynamic backend URL
    networks:
      - mern-network

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo_data: {}
