version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongo:27017/library_management
    networks:
      - mern-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mern-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
